### ISSUE TITLE
Plugin Not working

### ISSUE THREAD

**Issue by arslanakhter** [ethitter/jetpack-photon-for-nextgen#1]
Hi,

I have tested the plugin and its not working with new version of nextgen gallery. Kindly update the plugin. Thanks in Advance

**Comment by ethitter** [comment]
I've chosen to close this plugin rather than continue maintaining it. NextGen Gallery is regularly found to have security vulnerabilities, and I cannot enable anyone to continue using it. 

See:
* https://jetpack.com/features/security/library/nextgen-gallery-plugin/
* https://www.wordfence.com/blog/2021/02/severe-vulnerabilities-patched-in-nextgen-gallery-affect-over-800000-wordpress-sites/
